// Generated by CoffeeScript 1.10.0
(function() {
  require("angular");

  require("angular-route");

  require("angular-messages");

  require("angular-animate");

  require("angular-aria");

  require("angular-material");

  angular.module('app', ['ngRoute', 'ngMessages', 'ngAnimate', 'ngAria', 'ngMaterial']);

}).call(this);

//# sourceMappingURL=app.js.map
