// Generated by CoffeeScript 1.10.0
(function() {
  var IndexController,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('app').controller('mainCtrl', IndexController = (function() {
    IndexController.$inject = ['$mdIcon', '$mdSidenav', '$scope', '$filter', '$http', '$log', '$location', '$mdDialog', 'cart', 'breadcrumb', 'user'];

    function IndexController(mdIcon, mdSidenav, scope, filter, http, log, location, mdDialog, cart, breadcrumb, user) {
      this.mdIcon = mdIcon;
      this.mdSidenav = mdSidenav;
      this.scope = scope;
      this.filter = filter;
      this.http = http;
      this.log = log;
      this.location = location;
      this.mdDialog = mdDialog;
      this.cart = cart;
      this.breadcrumb = breadcrumb;
      this.user = user;
      this.showAdd = bind(this.showAdd, this);
      this.updateBreadcrumb = bind(this.updateBreadcrumb, this);
      this.sidenavToggle = bind(this.sidenavToggle, this);
      this.scope.user = this.user;
      this.scope.breadcrumb = this.breadcrumb;
      this.scope.cart = this.cart;
      this.scope.buttonsrc = "img/icon/add.svg";
      this.scope.menuItems = [
        {
          icon: 'img/icon/products.svg',
          title: 'Products',
          href: '/Website/'
        }, {
          icon: 'img/icon/cart.svg',
          title: 'Cart',
          href: 'Cart/' + this.user.loggedUser.userId
        }
      ];
      this.scope.userItems = [
        {
          icon: 'img/icon/hamburger.svg',
          title: 'Orders'
        }, {
          icon: 'img/icon/balance.svg',
          title: 'Credits'
        }, {
          icon: 'img/icon/settings.svg',
          title: 'Settings'
        }
      ];
      angular.extend(this.scope, {
        sidenavToggle: this.sidenavToggle,
        updateBreadcrumb: this.updateBreadcrumb,
        showAdd: this.showAdd
      });
    }

    IndexController.prototype.sidenavToggle = function() {
      return this.mdSidenav('sideNav').toggle();
    };

    IndexController.prototype.updateBreadcrumb = function(index) {
      return this.breadcrumb.splice(index + 1, this.breadcrumb.length - index - 1);
    };

    IndexController.prototype.showAdd = function(ev) {
      if (this.user.loggedUser.userId < 0) {
        return this.mdDialog.show({
          controller: 'loginCtrl',
          templateUrl: 'ngview/login/login.html',
          targetEvent: ev,
          clickOutsideToClose: true,
          onRemoving: function() {
            if (this.user.loggedUser.userId > 0) {
              return this.scope.buttonsrc = "img/icon/account.svg";
            }
          }
        });
      } else {
        return this.mdDialog.show({
          controller: 'logoutCtrl',
          templateUrl: 'ngview/logout/logout.html',
          targetEvent: ev,
          clickOutsideToClose: true,
          onRemoving: function() {
            if (this.user.loggedUser.userId === -1) {
              return this.scope.buttonsrc = "img/icon/add.svg";
            }
          }
        });
      }
    };

    return IndexController;

  })());

}).call(this);

//# sourceMappingURL=index.js.map
