// Generated by CoffeeScript 1.10.0
(function() {
  var CategoryController,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('app').controller('categoryCtrl', CategoryController = (function() {
    CategoryController.$inject = ['$scope', '$http', '$log', '$location', 'cart', 'breadcrumb', 'server', 'debug'];

    function CategoryController(scope, http, log, location, cart, breadcrumb, server, debug) {
      var url;
      this.scope = scope;
      this.http = http;
      this.log = log;
      this.location = location;
      this.cart = cart;
      this.breadcrumb = breadcrumb;
      this.server = server;
      this.debug = debug;
      this.addBreadcrumb = bind(this.addBreadcrumb, this);
      this.scope.categories = [];
      this.scope.error = {
        show: false,
        message: ''
      };
      if (this.debug.debug) {
        this.debug.categoryPush(this.scope.categories);
      } else {
        url = 'http://' + this.server.serverIp + ':' + this.server.port + '/productCategories/search/findByParentId';
        this.log.debug('Preform GET request for productcategorie with url: ' + url);
        this.http.get(url).then((function(_this) {
          return function(response) {
            var i, item, len, ref, results;
            _this.log.debug('Response of GET request: ');
            _this.log.debug(response);
            ref = response._embedded.productCategories;
            results = [];
            for (i = 0, len = ref.length; i < len; i++) {
              item = ref[i];
              results.push(_this.scope.categories.push(item));
            }
            return results;
          };
        })(this));
      }
      angular.extend(this.scope, {
        addBreadcrumb: this.addBreadcrumb
      });
    }

    CategoryController.prototype.addBreadcrumb = function(title, id) {
      this.location.path('/Products/' + id);
      return this.breadcrumb.push({
        text: title,
        path: '/' + id
      });
    };

    return CategoryController;

  })());

}).call(this);

//# sourceMappingURL=category.js.map
