// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').factory('breadcrumb', function() {
    return [
      {
        text: 'Home',
        path: '/'
      }
    ];
  });

}).call(this);

//# sourceMappingURL=breadcrumb.js.map
