// Generated by CoffeeScript 1.10.0
(function() {
  var Cart;

  angular.module('app').service('cart', Cart = (function() {
    function Cart() {
      this.orderId = '';
      this.order = {
        code: '',
        statusId: 1,
        machineId: null,
        userId: 1
      };
      this.products = {
        items: []
      };
    }

    return Cart;

  })());

}).call(this);

//# sourceMappingURL=cart.js.map
