// Generated by CoffeeScript 1.10.0
(function() {
  var Server;

  angular.module('app').service('server', Server = (function() {
    function Server() {
      this.serverIp = '10.0.0.121';
      this.port = 8080;
      this.debug = false;
    }

    return Server;

  })());

}).call(this);

//# sourceMappingURL=server.js.map
