// Generated by CoffeeScript 1.10.0
(function() {
  var User;

  angular.module('app').service('user', User = (function() {
    function User() {
      this.currentUser = {
        userId: -1,
        name: '',
        email: '',
        telephone: '',
        username: '',
        password: '',
        nfcCards: []
      };
      this.loggedUser = {
        userId: -1,
        name: 'Login',
        email: '',
        telephone: '',
        username: '',
        password: '',
        nfcCards: []
      };
    }

    return User;

  })());

}).call(this);

//# sourceMappingURL=user.js.map
