// Generated by CoffeeScript 1.10.0
(function() {
  var LogoutController,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('app').controller('logoutCtrl', LogoutController = (function() {
    LogoutController.$inject = ['$scope', '$http', '$log', '$location', '$mdDialog', 'user', 'server'];

    function LogoutController(scope, http, log, location, mdDialog, user, server) {
      this.scope = scope;
      this.http = http;
      this.log = log;
      this.location = location;
      this.mdDialog = mdDialog;
      this.user = user;
      this.server = server;
      this.logout = bind(this.logout, this);
      this.cancel = bind(this.cancel, this);
      angular.extend(this.scope, {
        logout: this.logout,
        cancel: this.cancel
      });
    }

    LogoutController.prototype.cancel = function() {
      return this.mdDialog.hide();
    };

    LogoutController.prototype.logout = function() {
      this.user.currentUser = {
        userId: -1,
        name: '',
        email: '',
        telephone: '',
        username: '',
        password: '',
        balance: 0.0,
        nfcCards: []
      };
      this.user.loggedUser = {
        userId: -1,
        name: 'Login',
        email: '',
        telephone: '',
        username: '',
        password: '',
        balance: 0.0,
        nfcCards: []
      };
      this.log.debug('User is logged out');
      this.mdDialog.hide();
      return this.location.path('/');
    };

    return LogoutController;

  })());

}).call(this);

//# sourceMappingURL=logout.js.map
