// Generated by CoffeeScript 1.10.0
(function() {
  var ProductController,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  angular.module('app').controller('productCtrl', ProductController = (function() {
    ProductController.$inject = ['$scope', '$http', '$log', '$routeParams', '$mdToast', 'cart', 'server'];

    function ProductController(scope, http, log, routeParams, mdToast, cart, server) {
      var url;
      this.scope = scope;
      this.http = http;
      this.log = log;
      this.routeParams = routeParams;
      this.mdToast = mdToast;
      this.cart = cart;
      this.server = server;
      this.debug = bind(this.debug, this);
      this.addToCart = bind(this.addToCart, this);
      this.scope.products = [];
      if (this.routeParams.categoryId > '0') {
        url = 'http://' + this.server.serverIp + ':' + this.server.port + '/products/search/findByProductCategoryId?productCategoryId=' + this.routeParams.categoryId;
        this.log.debug('Preform GET request for products with url: ' + url);
        this.http.get(url).success((function(_this) {
          return function(response) {
            var i, item, len, ref, results;
            _this.log.debug('Response of GET request: ');
            _this.log.debug(response);
            ref = response._embedded.products;
            results = [];
            for (i = 0, len = ref.length; i < len; i++) {
              item = ref[i];
              results.push(_this.scope.products.push(item));
            }
            return results;
          };
        })(this));
      }
      if (this.server.debug === true) {
        this.debug();
      }
      angular.extend(this.scope, {
        addToCart: this.addToCart,
        debug: this.debug
      });
    }

    ProductController.prototype.addToCart = function(item) {
      var i, len, product, ref, toast;
      toast = this.mdToast.simple().content('Product added: ' + item.name).hideDelay(500).position("top right");
      this.mdToast.show(toast);
      ref = this.cart.products.items;
      for (i = 0, len = ref.length; i < len; i++) {
        product = ref[i];
        if (product.productId === item.productId) {
          product.amount++;
          return;
        }
      }
      return this.cart.products.items.push({
        orderId: '',
        productId: item.productId,
        name: item.name,
        amount: 1,
        price: item.price
      });
    };

    ProductController.prototype.debug = function() {
      if (this.routeParams.categoryId === '-2') {
        this.scope.products.push({
          productId: -1,
          name: "Fries",
          description: "Puntzak frites",
          price: 1.5,
          productCategoryId: this.routeParams.categoryID,
          src: 'img/food/fries.jpeg'
        });
        return this.scope.products.push({
          productId: -2,
          name: "Hamburger",
          description: "Broodje Hamburger",
          price: 2.4,
          productCategoryId: this.routeParams.categoryID,
          src: 'img/food/hamburger.jpg'
        });
      } else if (this.routeParams.categoryId === '-1') {
        this.scope.products.push({
          productId: -3,
          name: "Fanta",
          description: "Blikje Fanta",
          price: 1.8,
          productCategoryId: this.routeParams.categoryID,
          src: 'img/drinks/fanta.jpg'
        });
        return this.scope.products.push({
          productId: -4,
          name: "Cola",
          description: "Blikje Cola",
          price: 2.2,
          productCategoryId: this.routeParams.categoryID,
          src: 'img/drinks/cola.jpg'
        });
      }
    };

    return ProductController;

  })());

}).call(this);

//# sourceMappingURL=products.js.map
