// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').config(function($mdThemingProvider, $mdIconProvider, $logProvider) {
    var customBlueMap;
    customBlueMap = $mdThemingProvider.extendPalette('light-blue', {
      'contrastDefaultColor': 'light',
      'contrastDarkColors': ['50'],
      '50': 'ffffff'
    });
    $mdThemingProvider.definePalette('customBlue', customBlueMap);
    $mdThemingProvider.theme('default').primaryPalette('customBlue', {
      'default': '500',
      'hue-1': '50'
    }).accentPalette('pink');
    $mdThemingProvider.theme('input', 'default').primaryPalette('grey');
    $mdIconProvider.defaultIconSet('img/action-icons.svg');
    return $logProvider.debugEnabled(true);
  });

}).call(this);

//# sourceMappingURL=config.js.map
