// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').config(function($httpProvider) {
    return $httpProvider.interceptors.push(function($q, $log) {
      return {
        'requestError': function(rejection) {
          $log.debug('RequestError ' + rejection.status);
          return $q.rejection;
        },
        'responseError': function(rejection) {
          $log.debug('ResponseError ' + rejection.status);
          return $q.rejection;
        }
      };
    });
  });

}).call(this);

//# sourceMappingURL=error.js.map
