// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').filter('sumByDoubleKey', function() {
    return function(data, key1, key2) {
      var i, item, len, sum;
      if (typeof data === 'undefined' || typeof key1 === 'undefined' || typeof key2 === 'undefined') {
        return 0;
      }
      sum = 0;
      for (i = 0, len = data.length; i < len; i++) {
        item = data[i];
        sum += parseFloat(item[key1]) * parseFloat(item[key2]);
      }
      return sum;
    };
  });

}).call(this);

//# sourceMappingURL=sumByDoubleKey.js.map
