// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').filter('sumByKey', function() {
    return function(data, key) {
      var i, item, len, sum;
      if (typeof data === 'undefined' || typeof key === 'undefined') {
        return 0;
      }
      sum = 0;
      for (i = 0, len = data.length; i < len; i++) {
        item = data[i];
        sum += parseInt(item[key]);
      }
      return sum;
    };
  });

}).call(this);

//# sourceMappingURL=sumByKey.js.map
