// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('app').directive('breadcrumb', function() {
    return {
      restrict: 'E',
      templateUrl: 'index/directive/breadcrumb.html'
    };
  });

}).call(this);

//# sourceMappingURL=breadcrumb.js.map
